FROM ubuntu:20.04
COPY build.hysteria /usr/local/bin/build.sh
WORKDIR /usr/local/bin/ 
RUN set -ex \
  && apt-get update \
  && apt-get install wget ca-certificates -y
RUN ["/usr/local/bin/build.sh"]
ENTRYPOINT ["/usr/local/bin/hysteria"]