FROM golang:1.19.1-bullseye as builder
RUN set -ex \
  && go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest \
  && xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
FROM ubuntu:20.04 
COPY --from=builder /go/caddy /usr/local/bin/caddy
COPY build.naiveproxy /usr/local/bin/build.sh
RUN set -ex \
  && apt-get update \
  && apt-get install wget libnss3-dev ca-certificates -y
RUN ["/usr/local/bin/build.sh"]