FROM teddysun/xray as builder
FROM ubuntu:20.04
COPY --from=builder  /usr/bin/xray /usr/local/bin/xray
WORKDIR /usr/local/bin/
RUN set -ex \
&& apt-get update \
&& apt-get install wget ca-certificates -y \
&& wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat \
&& wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
ENTRYPOINT ["/usr/local/bin/xray"]